# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xsolla < Formula
  desc "Xsolla CLI - manage Xsolla services from the command line"
  homepage "https://developers.xsolla.com/doc/cli"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xsolla/xsolla-cli/releases/download/v1.0.0/xsolla_1.0.0_darwin_amd64.tar.gz"
      sha256 "2d6fb4051e8a77cf67e04d068dcc708c697dcf0de68fc5aa2fa8192ef0558051"

      define_method(:install) do
        bin.install "xsolla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xsolla/xsolla-cli/releases/download/v1.0.0/xsolla_1.0.0_darwin_arm64.tar.gz"
      sha256 "477afd4617dd6f71bf9618dfb76d67995b6deded146bd64a13f1fcd2bc72f996"

      define_method(:install) do
        bin.install "xsolla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xsolla/xsolla-cli/releases/download/v1.0.0/xsolla_1.0.0_linux_amd64.tar.gz"
      sha256 "4569d0d04242abd642ed53904132fc7806ddedd6d87d822612124141a4863719"
      define_method(:install) do
        bin.install "xsolla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xsolla/xsolla-cli/releases/download/v1.0.0/xsolla_1.0.0_linux_arm64.tar.gz"
      sha256 "ad571c30ac3908f524eeeea6c695200dfeba8a6cbe90724b11e04c5f1d7d96a8"
      define_method(:install) do
        bin.install "xsolla"
      end
    end
  end

  test do
    system "#{bin}/xsolla", "version"
  end
end
